# Workflow name
name: Deploy spring code to aws elastic beanstalk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build with gradlew
        run: ./gradlew clean bootJar

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/Alledrogo_Spring_Lab-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      # deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: AKIA5RLTPQK5OJ43WBHV
          aws_secret_key: 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
          application_name: test-harmpro
          environment_name: Test-harmpro-env-prod
          version_label: ${{ github.SHA }}
          region: ue-north-1
          deployment_package: Alledrogo_Spring_Lab-0.0.1-SNAPSHOT.jar
